{% set name = "cleanlab" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c9ec2e2dc2f46b9aaaa46d8b4f0f2c1c080f15997dc1a6cf517fedbe19773d9

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.4
  run:
    - numpy >=1.11.3
    - python =2.7|>=3.4
    - scikit-learn >=0.18
    - scipy >=1.1.0
    - tqdm >=4.53.0

test:
  imports:
    - cleanlab
    - cleanlab.models

about:
  home: https://github.com/cgnorthcutt/cleanlab
  license: MIT
  license_family: MIT
  license_file: LICENSE # license not included in tarball, issue open on github here: https://github.com/cgnorthcutt/cleanlab/issues/24
  summary: Find label errors in datasets, weak supervision, and learning with noisy labels. Works for all datasets and models.
  doc_url: https://pypi.org/project/cleanlab/#description
  dev_url: https://github.com/cgnorthcutt/cleanlab
  description: |
    cleanlab is a machine learning python package for learning with noisy labels and finding label errors in datasets.
    cleanlab CLEANs LABels. It is powered by the theory of confident learning. Using the confidentlearning-reproduce 
    repo, cleanlab v0.1.0 reproduces results in the CL paper.

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
